import streamlit as st

st.title("Breast Cancer Classification")

st.write("""
    A breast cancer classification using the data from fine needle aspiration (FNA) biopsy
    """)

radius_m = st.number_input('Enter the mean radius')
texture_m = st.number_input('Enter the mean texture')
perimeter_m = st.number_input('Enter the mean perimeter')
area_m = st.number_input('Enter the mean area')
smoothness_m = st.number_input('Enter the mean smoothness')
compactness_m = st.number_input('Enter the mean compactness')
concavity_m = st.number_input('Enter the mean concavity')
concave_points_m = st.number_input('Enter the mean concave points')
symmetry_m = st.number_input('Enter the mean symmetry')
fractal_dimension_m = st.number_input('Enter the mean fractal dimension')
radius_se = st.number_input('Enter a number')
texture_se = st.number_input('Enter a number')
perimeter_se = st.number_input('Enter a number')
area_se = st.number_input('Enter a number')
smoothness_se = st.number_input('Enter a number')
compactness_se = st.number_input('Enter a number')
concavity_se = st.number_input('Enter a number')
concave_points_se = st.number_input('Enter a number')
symmetry_se = st.number_input('Enter a number')
fractal_dimension_se = st.number_input('Enter a number')
radius_w = st.number_input('Enter a number')
texture_w = st.number_input('Enter a number')
perimeter_w = st.number_input('Enter a number')
area_w = st.number_input('Enter a number')
smoothness_w = st.number_input('Enter a number') 
compactness_w = st.number_input('Enter a number')
concavity_w = st.number_input('Enter a number')
concave_points_w = st.number_input('Enter a number')
symmetry_w = st.number_input('Enter a number')
fractal_dimension_w = st.number_input('Enter a number')
